### ISSUE TITLE
These are 💯 

### ISSUE THREAD

**Issue by yazinsai** [volskaya/form_fields.dart#1]
Awesome work, just wanted to say thank you for sharing these!

**Comment by volskaya** [comment]
Oh man @yazinsai thanks! :sweat_smile: I forgot I have these repos public. I hope you can use this code somehow, but this is just a backup, the imports are written for offline use. And if you edit them manually, my repos will still break, because they'll expect my flutter fork.

But that being said, these form fields seem self contained enough to just copy paste the ones you need and replace the missing bits. :sweat_smile:

Thanks again, hope you're doing well!

**Comment by yazinsai** [comment]
Very useful nonetheless, @volskaya!

While I have you here, please email me when you get a chance (yazin@amalinvest.com). Tried reaching you a couple of times, but the inbox bounced

Have a great evening!
